version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: livestream_db
      POSTGRES_USER: livestream_user
      POSTGRES_PASSWORD: livestream_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 --workers 3 --timeout 120 livestream_project.wsgi:application
    volumes:
      - .:/app
      - recordings:/var/recordings
    environment:
      DEBUG: 'True'
      DJANGO_SETTINGS_MODULE: livestream_project.settings
      DATABASE_URL: postgres://livestream_user:livestream_pass@db:5432/livestream_db
    ports:
      - "8000:8000"
    depends_on:
      - db

  celery:
    build: .
    command: celery -A livestream_project worker -l info
    volumes:
      - .:/app
      - recordings:/var/recordings
    environment:
      DEBUG: 'True'
      DJANGO_SETTINGS_MODULE: livestream_project.settings
      DATABASE_URL: postgres://livestream_user:livestream_pass@db:5432/livestream_db
    depends_on:
      - db

volumes:
  postgres_data:
  recordings: 